citizenRequests:
  high-biodiversity-tiles:
    en: "Large wetlands provide homes for wildlife and native plants, and increase biodiversity."
    de: "Große Feuchtgebiete bieten Tieren und heimischen Pflanzen ein Zuhause und erhöhen die Biodiversität."
    group: biodiversity
    urgent: false
  enough-acceptable-biodiversity-regions:
    en: "Some zones have low biodiversity. They lack natural areas, like wetlands or forests."
    de: "Manche Gegenden haben eine geringe Biodiversität. Es fehlen Naturflächen wie Feuchtgebiete oder Wälder."
    group: biodiversity
    urgent: false
  enough-solar-farms:
    en: "Solar Farms can provide renewable energy and improve our carbon balance."
    de: "Solarparks können erneuerbare Energie liefern und unsere CO₂-Bilanz verbessern."
    group: carbon
    urgent: false
  enough-forests:
    en: "Forests can improve our carbon balance, because trees capture CO₂ from the air."
    de: "Wälder können unsere CO₂-Bilanz verbessern, weil Bäume CO₂ aus der Luft speichern."
    group: carbon
    urgent: false
  reduce-emissions:
    en: "We need to limit emissions from factories and livestock farms to improve our carbon balance."
    de: "Wir müssen die Emissionen aus Fabriken und Viehhaltung begrenzen, um unsere CO₂-Bilanz zu verbessern."
    group: carbon
    urgent: false
  enough-workers:
    en: "To grow our economy we need more workers. We should expand urban areas to increase the population."
    de: "Für unser Wirtschaftswachstum brauchen wir mehr Arbeitskräfte. Mehr Stadtgebiete vergrößern die Bevölkerung."
    group: economy
    urgent: false
  high-productivity:
    en: "To grow our economy we need more factories, large farms and forests."
    de: "Für unser Wirtschaftswachstum brauchen wir mehr Fabriken, große Bauernhöfe und Wälder."
    group: economy
    urgent: false
  food-plant-half-requirement:
    en: "We don’t produce enough food for our population. We should use more land for farming."
    de: "Unsere Lebensmittelproduktion reicht für die Bevölkerung nicht aus. Wir sollten mehr Land für Landwirtschaft nutzen."
    group: food-production
    urgent: true
  food-animal-half-requirement:
    en: "We are not producing enough meat, dairy and eggs to meet the demand. We need more livestock farms."
    de: "Wir produzieren nicht genug Fleisch, Eier und Milch. Wir brauchen mehr Viehhaltung."
    group: food-production
    urgent: true
  food-plant-full-requirement:
    en: "We don’t produce enough food for our population. We should use more land for farming."
    de: "Unsere Lebensmittelproduktion reicht für die Bevölkerung nicht aus. Wir sollten mehr Land für Landwirtschaft nutzen."
    group: food-production
    urgent: false
  food-animal-full-requirement:
    en: "We are not producing enough meat, dairy and eggs to meet the demand. We need more livestock farms."
    de: "Wir produzieren nicht genug Fleisch, Eier und Milch. Wir brauchen mehr Viehhaltung."
    group: food-production
    urgent: false
  sufficient-feed-percentage:
    en: "We are not producing enough food to feed the cattle in our livestock farms. We need more crops."
    de: "Wir produzieren zu wenig Futter für die Viehhaltung. Wir brauchen mehr Nutzpflanzen."
    group: food-production
    urgent: false
  urban-pollution:
    en: "Quality of life is affected by smells, pollution, and ugly sights. We should distance urban and industrial areas."
    de: "Gestank, dreckige Luft und häßliche Aussicht senken die Lebensqualität. Industrie raus aus der Stadt!"
    group: quality-of-life
    urgent: false
  urban-nature-proximity:
    en: "The quality of life in cities increases when there are forests and bodies of water nearby."
    de: "Wälder und Gewässer in Stadtnähe steigern die Lebensqualität."
    group: quality-of-life
    urgent: false
  urban-parks:
    en: "Having access to nature inside the city increases quality of life."
    de: "Zugang zu Natur im Stadtgebiet erhöht die Lebensqualität."
    group: quality-of-life
    urgent: false
  enough-urban-high-density:
    en: "A denser city, with taller buildings, reduces the distances people need to travel, and increases quality of life."
    de: "Eine dichtere Stadt mit höheren Gebäuden verkürzt die Wege für die Menschen und erhöht die Lebensqualität."
    group: quality-of-life
    urgent: false
  reduce-urban-sprawl:
    en: "A more concentrated urban area reduces the need for cars, increasing quality of life."
    de: "Ein kompakteres Stadtgebiet verringert den Bedarf an Autos und erhöht die Lebensqualität."
    group: quality-of-life
    urgent: false
citizenIcons:
  regular:
    - static/openmoji/bw/man-beard.svg
    - static/openmoji/bw/man-older.svg
    - static/openmoji/bw/man-raising-hand.svg
    - static/openmoji/bw/man.svg
    - static/openmoji/bw/person-bald.svg
    - static/openmoji/bw/person.svg
    - static/openmoji/bw/person-raising-hand.svg
    - static/openmoji/bw/person-older.svg
    - static/openmoji/bw/person-curly.svg
    - static/openmoji/bw/woman-older.svg
    - static/openmoji/bw/woman-raising-hand.svg
    - static/openmoji/bw/woman.svg
    - static/openmoji/bw/woman-curly.svg
    - static/openmoji/bw/woman-headscarf.svg
  urgent:
    - static/openmoji/bw/person-frowning.svg
    - static/openmoji/bw/woman-frowning.svg
    - static/openmoji/bw/man-frowning.svg
tileReferences: {}
