goals:
  carbon:
    index-thresholds:
      # Threshold values (average carbon < threshold) for each index level
      5: 0.2
      4: 0.5
      3: 1
      2: 2
      # 1 is the default
    # Suggested percentage of tiles that should be solar farms
    enough-solar-farms-percentage: 4
    # Suggested percentage of tiles that should be forests
    enough-forests-percentage: 20
  economic-growth:
    index-thresholds:
      # Threshold values (average productivity > threshold) for each index level
      5: 1.1
      4: 0.8
      3: 0.5
      2: 0.2
  biodiversity:
    # Minimum biodiversity value for a tile to be considered "high biodiversity"
    high-biodiversity-threshold: 5
    # Minium acceptable biodiversity value
    min-acceptable-biodiversity: 3
    # Percentage of tiles that should have high biodiversity to raise the index by
    # n points
    index-high-biodiversity-percentage:
      2: 4
      1: 2
    # Percentage of regions (4x4 tile blocks) that should have acceptable biodiversity to raise the
    # index by n points
    index-region-biodiversity-percentage:
      2: 60
      1: 30
  food-production:
    # Maximum percentage of plant-based food grown that might be used for feed
    max-feed-percentage: 50
    food-per-capita-factor: 1
    meat-base-req-percentage: 33
    index:
      partial-plant-goal: 0.5
      partial-animal-goal: 0.5
  quality-of-life:
    index-thresholds:
      5:
        max-urban-pollution-average: 0.2
        min-urban-nature-proximity-percent: 50
        min-urban-parks-percent: 3
        min-urban-high-percent: 20
        min-urban-density-average: 2
      4:
        max-urban-pollution-average: 0.4
        min-urban-nature-proximity-percent: 30
        min-urban-parks-percent: 2
        min-urban-high-percent: 10
        min-urban-density-average: 1.6
      3:
        max-urban-pollution-average: 0.6
        min-urban-nature-proximity-percent: 15
        min-urban-parks-percent: 1
      2:
        max-urban-pollution-average: 0.8
